// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transceiver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OggOpusData   []byte                 `protobuf:"bytes,1,opt,name=ogg_opus_data,json=oggOpusData,proto3" json:"ogg_opus_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_transceiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transceiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_transceiver_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetOggOpusData() []byte {
	if x != nil {
		return x.OggOpusData
	}
	return nil
}

var File_transceiver_proto protoreflect.FileDescriptor

const file_transceiver_proto_rawDesc = "" +
	"\n" +
	"\x11transceiver.proto\x12\vtransceiver\"0\n" +
	"\n" +
	"AudioChunk\x12\"\n" +
	"\rogg_opus_data\x18\x01 \x01(\fR\voggOpusData2U\n" +
	"\x12TransceiverService\x12?\n" +
	"\aConnect\x12\x17.transceiver.AudioChunk\x1a\x17.transceiver.AudioChunk(\x010\x01B Z\x1eradio-bridge-test-client/protob\x06proto3"

var (
	file_transceiver_proto_rawDescOnce sync.Once
	file_transceiver_proto_rawDescData []byte
)

func file_transceiver_proto_rawDescGZIP() []byte {
	file_transceiver_proto_rawDescOnce.Do(func() {
		file_transceiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transceiver_proto_rawDesc), len(file_transceiver_proto_rawDesc)))
	})
	return file_transceiver_proto_rawDescData
}

var file_transceiver_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transceiver_proto_goTypes = []any{
	(*AudioChunk)(nil), // 0: transceiver.AudioChunk
}
var file_transceiver_proto_depIdxs = []int32{
	0, // 0: transceiver.TransceiverService.Connect:input_type -> transceiver.AudioChunk
	0, // 1: transceiver.TransceiverService.Connect:output_type -> transceiver.AudioChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transceiver_proto_init() }
func file_transceiver_proto_init() {
	if File_transceiver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transceiver_proto_rawDesc), len(file_transceiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transceiver_proto_goTypes,
		DependencyIndexes: file_transceiver_proto_depIdxs,
		MessageInfos:      file_transceiver_proto_msgTypes,
	}.Build()
	File_transceiver_proto = out.File
	file_transceiver_proto_goTypes = nil
	file_transceiver_proto_depIdxs = nil
}
