// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: transceiver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransceiverService_Connect_FullMethodName = "/transceiver.TransceiverService/Connect"
)

// TransceiverServiceClient is the client API for TransceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransceiverServiceClient interface {
	// 双方向ストリーミング: クライアントから音声を送信し、サーバーからも音声を受信する
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error)
}

type transceiverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransceiverServiceClient(cc grpc.ClientConnInterface) TransceiverServiceClient {
	return &transceiverServiceClient{cc}
}

func (c *transceiverServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransceiverService_ServiceDesc.Streams[0], TransceiverService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, AudioChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransceiverService_ConnectClient = grpc.BidiStreamingClient[AudioChunk, AudioChunk]

// TransceiverServiceServer is the server API for TransceiverService service.
// All implementations must embed UnimplementedTransceiverServiceServer
// for forward compatibility.
type TransceiverServiceServer interface {
	// 双方向ストリーミング: クライアントから音声を送信し、サーバーからも音声を受信する
	Connect(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error
	mustEmbedUnimplementedTransceiverServiceServer()
}

// UnimplementedTransceiverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransceiverServiceServer struct{}

func (UnimplementedTransceiverServiceServer) Connect(grpc.BidiStreamingServer[AudioChunk, AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedTransceiverServiceServer) mustEmbedUnimplementedTransceiverServiceServer() {}
func (UnimplementedTransceiverServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransceiverServiceServer will
// result in compilation errors.
type UnsafeTransceiverServiceServer interface {
	mustEmbedUnimplementedTransceiverServiceServer()
}

func RegisterTransceiverServiceServer(s grpc.ServiceRegistrar, srv TransceiverServiceServer) {
	// If the following call panics, it indicates UnimplementedTransceiverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransceiverService_ServiceDesc, srv)
}

func _TransceiverService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransceiverServiceServer).Connect(&grpc.GenericServerStream[AudioChunk, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransceiverService_ConnectServer = grpc.BidiStreamingServer[AudioChunk, AudioChunk]

// TransceiverService_ServiceDesc is the grpc.ServiceDesc for TransceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transceiver.TransceiverService",
	HandlerType: (*TransceiverServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _TransceiverService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transceiver.proto",
}
