[server]
listen_addr = "0.0.0.0:50051"

[gpio]
ptt_pin = 26

[audio]
output_device       = "plughw:0,0"
input_device        = "hw:0,0"
input_threshold_rms     = 1000
input_silence_ms        = 1000
input_max_recording_secs = 30

[timing]
ptt_on_delay_ms  = 500
ptt_off_delay_ms = 200
cooldown_ms      = 1000

[queue]
max_audio_duration_secs = 30
max_queue_size          = 10
